import { Button, Grid, Spacer, Text, useToasts } from "@geist-ui/react"
import { useRouter } from "next/router"
import { useState } from "react"
import OtpInput from 'react-otp-input'
import https from "https"
import { parseCookies, setCookie } from 'nookies'
import Layout from "../components/layout"
import NodeRSA from 'node-rsa'

const inputStyle = {
    borderRadius: '4px',
    width: '30px',
    height: '50px',
    margin: '8px',
    fontSize: '1.25rem',
    border: 'gray solid 1px'
}

const focusStyle = {
    border: '#2e2b2b solid 4px'
}

export default function ValidatePin({public_key, voterId}) {

    const router = useRouter()
    const [, setToast] = useToasts()

    const [otp, setOtp] = useState('')
    const [validating, setValidating] = useState(false)

    const handleOtpChange = e => setOtp(e)

    const checkPin = async () => {

        setValidating(true)

        const payload = {
            pin: otp,
            voterId: voterId
        }
        
        var key = new NodeRSA(public_key)
        const encryptedPayload = key.encrypt(payload, 'base64')

        const httpsAgent = new https.Agent({
            rejectUnauthorized: false,
        });

        fetch(`${process.env.NEXT_PUBLIC_API_URL}/voters/validate`,
            {
                agent: httpsAgent,
                method: 'POST',
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(encryptedPayload)
            })
            .then(res => {
                if (res.ok) {
                    res.json()
                        .then(t => {
                            if (!t.isCorrect) {
                                setValidating(false)
                                setToast({
                                    text: 'Validation failed. One-Time Password is invalid.',
                                    type: 'error'
                                })
                            } else {
                                setValidating(false)
                                setToast({
                                    text: 'Validation successful.',
                                    type: 'success'
                                })
                                setCookie(null, 'token', t.token, {
                                    maxAge: 3600
                                })
                                router.push('/verification')
                            }
                        })
                }
            })
            .catch(error => {
                setValidating(false)
            })
    }

    return (
        <Layout>
            <Text h2>Enter the 6 digit One-Time Password (OTP) that is generated by the authenticator application and click Validate</Text>
            <Grid.Container justify="center" gap={2}>
                <Grid>
                    <OtpInput value={otp}
                        onChange={handleOtpChange}
                        numInputs={6}
                        isInputNum={true}
                        isInputSecure={true}
                        shouldAutoFocus
                        inputStyle={inputStyle}
                        focusStyle={focusStyle} />
                </Grid>
            </Grid.Container>

            <Spacer y={1} />

            <Grid.Container justify="center">
                <Grid>
                    <Button type="secondary" onClick={checkPin} disabled={otp.length < 6} loading={validating} size="large" shadow>
                        <Text h3>Validate</Text>
                    </Button>
                </Grid>
            </Grid.Container>
        </Layout>
    )
}

export async function getServerSideProps(context) {
    const cookies = parseCookies(context)
    const public_key = cookies.public_key
    const voterId = cookies.voterId

    return {
        props: {
            public_key,
            voterId
        }
    }
}